# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Golang Build And Release
env:
  GPG_KEY_ID: ${{ secrets.MAVEN_SIGN_KEY_ID }}
  GPG_KEY: ${{ secrets.MAVEN_SIGN_KEY }}
  GPG_PWD: ${{ secrets.MAVEN_SIGN_KEY_PWD }}
  PUB_USER: ${{ secrets.MAVEN_USER_NAME }}
  PUB_PWD: ${{ secrets.MAVEN_USER_PWD }}
  GOARCH: amd64
  GOOS=linux
  BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
    - name: Go Build
        run: |
          mkdir -p output
          go build -ldflags="-w -s" -o "./output/tracing-sink" -i ./main/

    name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: ./output
        file: ./dockerfile
        tag_with_ref: true
        labels: |
          org.opencontainers.image.authors=labijie.com
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
        tags: |
          ${{ env.IMAGE }}:latest
        push: true
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.DOCKER_PASSWORD }}